name: Build Tauri App on Windows

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest  # Use Windows as the build environment

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22.x'  # Set Node.js version to 20.x

      - name: Install Yarn
        run: npm install --global yarn

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install Tauri Bundler
        run: cargo install tauri-cli

      - name: Install Dependencies
        run: yarn install

      - name: Build Tauri App
        run: yarn tauri build

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: tauri-app
          path: src-tauri/target/release/bundle/
